# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b4cbf8c8b688ed3f9c0c63cf2cc30b833304f603dc42ae1dc95391ef64eda0c596c9600c4b4b6ee36ecada36d8717de453f42d7dc22bead407ae4cc2f4daedf

test:
  secret_key_base: 742e126d76e49a679e08b3d35b1aac38a539b5d3a9e4a2692c62b550ec6a6c0e910d4b76ffb922402ce4f67b711d821eb3ceb9b322760cf4d80ff37440be533d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
